### ISSUE TITLE
Suppression de notes 

### ISSUE THREAD

**Issue by RenardFestif** [RenardFestif/2I013#8]
Suppression impossible ( Conflit avec la `SeekBar`) 
pas de pistes pour l'instant !

**Comment by ghost** [comment]
Le bug à été isolé dans la méthode addRemove de la classe Model.
Aucune modification n'a marché pour le moment.

**Comment by ghost** [comment]
BUG corrigé 👍 
Lors de l'ajout d'une note, on crée une nouvelle position en x + offset * pas.
Cependant la condition pour la supprimer n'était jamais respecté car on cherchait une position ayant déjà eu l'ajout de l'offset * pas.
Donc x+offset*pas != x

        for(int i=0;i<xys.size();i++){
            if(xys.get(i).getX()==x+offset*pas && xys.get(i).getY()==y) {
                xys.remove(i);
                partitionX.removeNote(position,caseX+offset, noteName);
                return;
            }
        }
        xys.add(new Position(x+(int)(offset*pas),y,d));
        partitionX.addNote(position, caseX+offset, noteName, d);
